/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GUI */

#ifndef _Included_GUI
#define _Included_GUI
#ifdef __cplusplus
extern "C" {
#endif
#undef GUI_FOCUS_TRAVERSABLE_UNKNOWN
#define GUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef GUI_FOCUS_TRAVERSABLE_DEFAULT
#define GUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef GUI_FOCUS_TRAVERSABLE_SET
#define GUI_FOCUS_TRAVERSABLE_SET 2L
#undef GUI_TOP_ALIGNMENT
#define GUI_TOP_ALIGNMENT 0.0f
#undef GUI_CENTER_ALIGNMENT
#define GUI_CENTER_ALIGNMENT 0.5f
#undef GUI_BOTTOM_ALIGNMENT
#define GUI_BOTTOM_ALIGNMENT 1.0f
#undef GUI_LEFT_ALIGNMENT
#define GUI_LEFT_ALIGNMENT 0.0f
#undef GUI_RIGHT_ALIGNMENT
#define GUI_RIGHT_ALIGNMENT 1.0f
#undef GUI_serialVersionUID
#define GUI_serialVersionUID -7644114512714619750i64
#undef GUI_serialVersionUID
#define GUI_serialVersionUID 4613797578919906343i64
#undef GUI_INCLUDE_SELF
#define GUI_INCLUDE_SELF 1L
#undef GUI_SEARCH_HEAVYWEIGHTS
#define GUI_SEARCH_HEAVYWEIGHTS 1L
#undef GUI_OPENED
#define GUI_OPENED 1L
#undef GUI_serialVersionUID
#define GUI_serialVersionUID 4497834738069338734i64
#undef GUI_DEFAULT_CURSOR
#define GUI_DEFAULT_CURSOR 0L
#undef GUI_CROSSHAIR_CURSOR
#define GUI_CROSSHAIR_CURSOR 1L
#undef GUI_TEXT_CURSOR
#define GUI_TEXT_CURSOR 2L
#undef GUI_WAIT_CURSOR
#define GUI_WAIT_CURSOR 3L
#undef GUI_SW_RESIZE_CURSOR
#define GUI_SW_RESIZE_CURSOR 4L
#undef GUI_SE_RESIZE_CURSOR
#define GUI_SE_RESIZE_CURSOR 5L
#undef GUI_NW_RESIZE_CURSOR
#define GUI_NW_RESIZE_CURSOR 6L
#undef GUI_NE_RESIZE_CURSOR
#define GUI_NE_RESIZE_CURSOR 7L
#undef GUI_N_RESIZE_CURSOR
#define GUI_N_RESIZE_CURSOR 8L
#undef GUI_S_RESIZE_CURSOR
#define GUI_S_RESIZE_CURSOR 9L
#undef GUI_W_RESIZE_CURSOR
#define GUI_W_RESIZE_CURSOR 10L
#undef GUI_E_RESIZE_CURSOR
#define GUI_E_RESIZE_CURSOR 11L
#undef GUI_HAND_CURSOR
#define GUI_HAND_CURSOR 12L
#undef GUI_MOVE_CURSOR
#define GUI_MOVE_CURSOR 13L
#undef GUI_NORMAL
#define GUI_NORMAL 0L
#undef GUI_ICONIFIED
#define GUI_ICONIFIED 1L
#undef GUI_MAXIMIZED_HORIZ
#define GUI_MAXIMIZED_HORIZ 2L
#undef GUI_MAXIMIZED_VERT
#define GUI_MAXIMIZED_VERT 4L
#undef GUI_MAXIMIZED_BOTH
#define GUI_MAXIMIZED_BOTH 6L
#undef GUI_serialVersionUID
#define GUI_serialVersionUID 2673458971256075116i64
#undef GUI_EXIT_ON_CLOSE
#define GUI_EXIT_ON_CLOSE 3L
/*
 * Class:     GUI
 * Method:    c_send
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GUI_c_1send
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GUI
 * Method:    c_receive
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GUI_c_1receive
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
