/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server */

#ifndef _Included_server
#define _Included_server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_server_getString
  (JNIEnv *, jobject);

/*
 * Class:     server
 * Method:    sendString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_server_sendString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
